version: "3"
services:
  directus:
    build: .
    ports:
      - 8055:8055
    depends_on:
      - database
  database:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=<Directuse database>
      - MYSQL_USER=<RaigoRobin12>
      - MYSQL_PASSWORD=<Raigo1234>
      - MYSQL_ROOT_PASSWORD=<Raigo12345>
  sentry:
    image: getsentry/sentry:latest
    environment:
      - SENTRY_SECRET_KEY=my-secret-key
      - SENTRY_POSTGRES_HOST=my-postgres-host
      - SENTRY_POSTGRES_PORT=my-postgres-port
      - SENTRY_POSTGRES_DB=my-postgres-database
      - SENTRY_POSTGRES_USER=my-postgres-user
      - SENTRY_POSTGRES_PASSWORD=my-postgres-password
