version: "3"
services:
  directus:
    image: directus/directus:v9
    ports:
      - 8055:8055
    depends_on:
      - database
    environment:
      - DIRECTUS_DATABASE_HOST=database
      - DIRECTUS_DATABASE_PORT=3306
      - DIRECTUS_DATABASE_NAME=<Directus database>
      - DIRECTUS_DATABASE_USERNAME=<RaigoRobin12>
      - DIRECTUS_DATABASE_PASSWORD=<Raigo1234>

  database:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=<Directus database>
      - MYSQL_USER=<RaigoRobin12>
      - MYSQL_PASSWORD=<Raigo1234>
      - MYSQL_ROOT_PASSWORD=<Raigo12345>

  sentry:
    image: getsentry/sentry:latest
    environment:
      - SENTRY_SECRET_KEY=my-secret-key
      - SENTRY_POSTGRES_HOST=my-postgres-host
      - SENTRY_POSTGRES_PORT=my-postgres-port
      - SENTRY_POSTGRES_DB=my-postgres-database
      - SENTRY_POSTGRES_USER=my-postgres-user
      - SENTRY_POSTGRES_PASSWORD=my-postgres-password
