name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Docker secrets
        run: |
          echo "::set-env name=DOCKER_USERNAME::your-docker-username"
          echo "::set-env name=DOCKER_PASSWORD::your-docker-password"

      - name: Build and push Docker image
        run: |
          docker build -t your-docker-image-tag .
          echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
          docker push your-docker-image-tag
